package academy.learnprogramming.controller;

import academy.learnprogramming.service.DemoService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Slf4j
@Controller
public class DemoController {

    // == fields ===
    private final DemoService demoService;

    // == constructors ==
    @Autowired
    public DemoController(DemoService demoService) {        //demoService should reference an injected instance of DemoServiceImpl (given that DemoServiceImpl is the only class within scope that implements the interface DemoService)

        this.demoService = demoService;
    }



    // == request methods ==
    // http://localhost:8080/todo-list/hello
    @ResponseBody
    @GetMapping("/hello")       // When /hello is appended to the URL entered into a browser, the incoming request will get mapped by the DispatcherServlet to this method
    public String hello()
    {
        return "hello";         // The string 'hello' is the 'view' that is return to incoming GET request
    }

    // http://localhost:8080/todo-list/welcome
    // http://localhost:8080/todo-list/welcome?user=Paul&age=28
    @GetMapping("welcome")      // The initial forward slash is not added given that it is already appended by the 'RESOLVER_PREFIX' in 'webconfig.java'
    public String welcome(@RequestParam String user, @RequestParam int age, Model model)      // Model is generated by the Dispatcher Servlet and can be viewed as a key:value pair or map.
    {
        model.addAttribute("helloMessage", demoService.getHelloMessage(user));
        model.addAttribute("age", age);

        log.info("model= {}", model);

        // prefix + name + suffix
        // /WEB-INF/view/welcome.jsp
        return "welcome";
    }

    // == model attributes ==
    @ModelAttribute("welcomeMessage")
    public String welcomeMessage(){
        log.info("welcomeMessage() called");

        return demoService.getWelcomeMessage();
    }
}
